Analyzing HTTP Headers
======================
Nathan Ladd <nathanladd@gmail.com>

The primary motivation for writing this library is to enable fast parsing of HTTP headers into semantic data structures in ruby. For instance, the +TE+ header in HTTP might look like this in an HTTP message:

 TE: trailers, compress; q=0.25, some-extension; foo; bar=baz; qux="quoted string"; q=1.0\r\n

Here is the associated grammar for just the field value (ignoring the leading +TE: + and trailing +\r\n+):

 TE = [ ( "," / t-codings ) *( OWS "," [ OWS t-codings ] ) ]
 t-codings = "trailers" / ( transfer-coding [ t-ranking ] )
 t-ranking = OWS ";" OWS "q=" rank
 transfer-coding = "chunked" / "compress" / "deflate" / "gzip" / transfer-extension
 transfer-extension = token *( OWS ";" OWS transfer-parameter )
 transfer-parameter = token BWS "=" BWS ( token / quoted-string )
 tchar = "!" / "#" / "$" / "%" / "&" / "'" / "*" / "+" / "-" / "." / "^" / "_" / "`" / "|" / "~" / DIGIT / ALPHA
 token = 1*tchar
 quoted-string = DQUOTE *( qdtext / quoted-pair ) DQUOTE
 qdtext = HTAB / SP / "!" / %x23-5B ; '#'-'[' / %x5D-7E ; ']'-'~' / obs-text
 quoted-pair = "\" ( HTAB / SP / VCHAR / obs-text )
 obs-text = %x80-FF
 rank = ( "0" [ "." *3DIGIT ] ) / ( "1" [ "." *3"0" ] )
 OWS = *( SP / HTAB )

By inspecting the grammer closely, we can also notice that some pretty weird combinations of characters are totally valid:

 TE: \r\n
 TE , trailers\r\n
 TE: ,,, , ,,, ,,,      ,, ,\r\n

Let's explore the ideal ruby parser for this header. Here's the usage:

[source,ruby]
----
te = "trailers, compress; q=0.25, some-extension; foo; bar=baz; qux="quoted string"; q=1.0"

TE.parse te
=> #<TE t_codings_list=[#<TCodings name="trailers", rank=1>, #<TCodings name="compress", rank=0.25>, …>
----

The input is the field value of the header, and the output is a tree of data structures representing the header itself. The benefit of data structures here is that HTTP libraries that need to make use of the header don't have to work with primitives. The actual class +TE+ is likely a subclass of +Struct+, and the root structure plus it's list of +t_codings+ constitutes something analogous to an abstract syntax tree; only we're not wanting to execute the tree as in the case of an interpreter.

What would a non-generalized, reasonably performant implementation of this parser look like?

[source,ruby]
----
te = "trailers, compress; q=0.25, some-extension; foo; bar=baz; qux="quoted string"; q=1.0"

output = TE.new

token = /[\!#$%&'\*\+\.^_`|~[:alnum:]]+/
delimiter = /\A[[:space:]]*,[[:space:]]*/
known_coding = /\Atrailers|chunked|compress|deflate|gzip/
rank = /\A[[:space:]]*;[[:space:]]*q=(?<rank>1(?:\.0{,3})?|0(?:[[:digit:]]{,3}))/

until te.empty?
  t_codings = TCodings.new

  if match_data = delemiter.match te
    te = match_data.post_match
    next # notice t_codings above is ignored
  elsif match_data = known_coding.match te
    t_codings.name = match_data.to_s
    te = match_data.post_match
  elsif match_data = token.match te
    extension = TransferExtension.new

    # parse through all the extensions
  end

  if match_data = rank.match te
    t_codings.rank = match_data[:rank].to_f
  end

  output.t_codings << t_codings
end
----

This gets pretty unwieldy.
